"""Render HTML + JSON reports."""
from __future__ import annotations
import json
from pathlib import Path
from jinja2 import Template

TEMPLATE = Template("""<!doctype html>
<html><head><meta charset="utf-8"><title>Movie Rating Analysis Report</title>
<style>
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:1000px;margin:2rem auto;padding:0 1rem;color:#222}
h1{border-bottom:2px solid #333;padding-bottom:.4rem}
h2{margin-top:2rem;color:#334}
table{border-collapse:collapse;width:100%;margin:1rem 0}
th,td{padding:.4rem .6rem;border-bottom:1px solid #ddd;text-align:left;font-size:.92rem}
th{background:#f4f4f8}
img{max-width:100%;border:1px solid #eee;border-radius:6px;margin:.5rem 0}
.kpis{display:flex;gap:1rem;flex-wrap:wrap}
.kpi{background:#f7f7fb;border-radius:8px;padding:.8rem 1rem;flex:1;min-width:160px}
.kpi b{display:block;font-size:1.4rem;color:#224}
footer{margin-top:3rem;color:#777;font-size:.85rem;text-align:center}
</style></head><body>
<h1>Movie Rating Analysis</h1>
<p><b>Author:</b> Sumit Kumar &nbsp;|&nbsp; <b>Intern ID:</b> CITS3958</p>
<div class="kpis">
  <div class="kpi"><b>{{ kpis.movies }}</b>Movies</div>
  <div class="kpi"><b>{{ kpis.ratings }}</b>Ratings</div>
  <div class="kpi"><b>{{ kpis.users }}</b>Unique users</div>
  <div class="kpi"><b>{{ '%.2f' % kpis.mean_rating }}</b>Global mean rating</div>
</div>
<h2>Rating distribution</h2><img src="rating_distribution.png">
<h2>Top {{ top|length }} movies</h2>
<table><tr><th>#</th><th>Title</th><th>Votes</th><th>Mean</th><th>Weighted</th></tr>
{% for r in top %}<tr><td>{{ loop.index }}</td><td>{{ r.title }}</td><td>{{ r.votes }}</td>
<td>{{ '%.2f' % r.mean }}</td><td>{{ '%.2f' % r.weighted }}</td></tr>{% endfor %}
</table>
<img src="top_movies.png">
<h2>Average rating by genre</h2><img src="genre_average.png">
<h2>Ratings over time</h2><img src="ratings_over_time.png">
<footer>Generated by the Movie Rating Analysis pipeline &middot; MIT License</footer>
</body></html>""")


def render(kpis: dict, top_rows: list[dict], out_dir: Path) -> Path:
    html = TEMPLATE.render(kpis=kpis, top=top_rows)
    out = out_dir / "report.html"
    out.write_text(html, encoding="utf-8")
    (out_dir / "summary.json").write_text(
        json.dumps({"kpis": kpis, "top": top_rows}, indent=2), encoding="utf-8")
    return out
